version: '3'
services:
  flask-api:
    depends_on:
      - postgresql
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: flask-api
    image: flask-app:latest
    restart: always
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "False"
      APP_PORT: 5000
    ports:
      - 8080:5000

  postgresql:
    environment:
      POSTGRES_USER: docker-api
      POSTGRES_PASSWORD: flaskAPIdocker
      POSTGRES_DB: flask_api
    restart: always
    image: postgres:12.6
    ports:
      - 5432:5432
    networks:
      - default
    volumes:
      - ./postgres-data:/var/lib/postgresql/data