version: '3'
services:
  flask-api:
    depends_on:
      - postgresql
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: flask-api
    image: flask-api:latest
    restart: unless-stopped
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_PORT: ${APP_PORT}
      SQLALCHEMY_DATABASE_URI: ${SQLALCHEMY_DATABASE_URI}
    ports:
      - "5000:5000"
    networks:
      - default

  postgresql:
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    container_name: postgresql
    restart: always
    image: postgres:12.6
    ports:
      - "5432:5432"
    networks:
      - default
    volumes:
      - ./postgres-data:/var/lib/postgresql/data